meta:
  numMorph: 7
m1:
  meta:
    numSensor: 11
  s1:
    type: ProximitySensor
    bearing: 40.0
    orientation: 0.0
  s2:
    type: ProximitySensor
    bearing: -40.0
    orientation: 0.0
  s3:
    type: ProximitySensor
    bearing: 140.0
    orientation: 0.0
  s4:
    type: ProximitySensor
    bearing: -140.0
    orientation: 0.0
  s5:
    type: ProximitySensor
    bearing: 180.0
    orientation: 0.0
  s6:
    type: UltrasonicSensor
    bearing: 0.0
    orientation: 0.0
  s7:
    type: UltrasonicSensor
    bearing: 90
    orientation: 0.0
  s8:
    type: UltrasonicSensor
    bearing: -90.0
    orientation: 0.0
  s9:
    type: ColourRangedSensor
    bearing: 15
    orientation: 0.0
  s10:
    type: LowResCameraSensor
    bearing: -15.0
    orientation: 0.0
  s11:
    type: ConstructionSensor
    bearing: 0.0
    orientation: 0.0
m2:
  meta:
    numSensor: 8
  s1:
    type: ProximitySensor
    bearing: 40.0
    orientation: 0.0
  s2:
    type: ProximitySensor
    bearing: -40.0
    orientation: 0.0
  s3:
    type: ProximitySensor
    bearing: 120.0
    orientation: 0.0
  s4:
    type: ProximitySensor
    bearing: -120.0
    orientation: 0.0
  s5:
    type: UltrasonicSensor
    bearing: 0.0
    orientation: 0.0
  s6:
    type: ConstructionSensor
    bearing: 0.0
    orientation: 0.0
  s7:
    type: ColourRangedSensor
    bearing: 0.0
    orientation: 0.0
  s8:
    type: LowResCameraSensor
    bearing: 0.0
    orientation: 0.0
m3:
  meta:
    numSensor: 8
  s1:
    type: ProximitySensor
    bearing: 10.0
    orientation: 0.0
  s2:
    type: ProximitySensor
    bearing: 180.0
    orientation: 0.0
  s3:
    type: UltrasonicSensor
    bearing: 0.0
    orientation: 0.0
  s4:
    type: UltrasonicSensor
    bearing: 90.0
    orientation: 0.0
  s5:
    type: ColourProximitySensor
    bearing: 0.0
    orientation: 0.0
  s6:
    type: ColourRangedSensor
    bearing: 0.0
    orientation: 0.0
  s7:
    type: LowResCameraSensor
    bearing: 0.0
    orientation: 0.0
  s8:
    type: ConstructionSensor
    bearing: 0.0
    orientation: 0.0
m4:
  meta:
    numSensor: 9
  s1:
    type: ProximitySensor
    bearing: 10.0
    orientation: 0.0
  s2:
    type: ProximitySensor
    bearing: 40.0
    orientation: 0.0
  s3:
    type: ProximitySensor
    bearing: 75.0
    orientation: 0.0
  s4:
    type: ProximitySensor
    bearing: 140.0
    orientation: 0.0
  s5:
    type: ProximitySensor
    bearing: 180.0
    orientation: 0.0
  s6:
    type: UltrasonicSensor
    bearing: 0.0
    orientation: 0.0
  s7:
    type: UltrasonicSensor
    bearing: 40.0
    orientation: 0.0
  s8:
    type: UltrasonicSensor
    bearing: 180.0
    orientation: 0.0
  s9:
    type: ConstructionSensor
    bearing: 0.0
    orientation: 0.0
m5:
  meta:
    numSensor: 4
  s1:
    type: ColourProximitySensor
    bearing: 0.0
    orientation: 0.0
  s2:
    type: ColourRangedSensor
    bearing: 0.0
    orientation: 0.0
  s3:
    type: LowResCameraSensor
    bearing: 0.0
    orientation: 0.0
  s4:
    type: ConstructionSensor
    bearing: 0.0
    orientation: 0.0
m6:
  meta:
    numSensor: 6
  s1:
    type: ColourProximitySensor
    bearing: 0.0
    orientation: 0.0
  s2:
    type: ColourRangedSensor
    bearing: 0.0
    orientation: 0.0
  s3:
    type: LowResCameraSensor
    bearing: 0.0
    orientation: 0.0
  s4:
    type: ConstructionSensor
    bearing: 0.0
    orientation: 0.0
  s5:
    type: ProximitySensor
    bearing: 90.0
    orientation: 0.0
  s6:
    type: ProximitySensor
    bearing: -90.0
    orientation: 0.0
m7:
  meta:
    numSensor: 10
  s1:
    type: ProximitySensor
    bearing: 40.0
    orientation: 0.0
  s2:
    type: ProximitySensor
    bearing: -40.0
    orientation: 0.0
  s3:
    type: ProximitySensor
    bearing: 75.0
    orientation: 0.0
  s4:
    type: ProximitySensor
    bearing: -75.0
    orientation: 0.0
  s5:
    type: ProximitySensor
    bearing: 180.0
    orientation: 0.0
  s6:
    type: UltrasonicSensor
    bearing: 0.0
    orientation: 0.0
  s7:
    type: UltrasonicSensor
    bearing: 90.0
    orientation: 0.0
  s8:
    type: UltrasonicSensor
    bearing: -90.0
    orientation: 0.0
  s9:
    type: ConstructionSensor
    bearing: 0.0
    orientation: 0.0
  s10:
    type: ColourRangedSensor
    bearing: 0.0
    orientation: 0.0