---
config0:
  resQuantity : 15 0 0
  resource0:
    left: A
    right: A
    up: A
    down: A
  resource1:
    left: X
    right: X
    up: X
    down: X
  resource2:
    left: X
    right: X
    up: X
    down: X
config1:
  resQuantity : 8 7 0
  resource0:
    left: A B
    right: A B
    up: A B
    down: A B
  resource1:
    left: A B
    right: A B
    up: A B
    down: A B
  resource2:
    left: X
    right: X
    up: X
    down: X
config2:
  resQuantity : 5 5 5
  resource0:
    left: A B C
    right: A B C
    up: A B C
    down: A B C
  resource1:
    left: A B C
    right: A B C
    up: A B C
    down: A B C
  resource2:
    left: A B C
    right: A B C
    up: A B C
    down: A B C
config3:
  resQuantity : 5 5 5
  resource0:
    left: A B C
    right: A B C
    up: A B C
    down: A B C
  resource1:
    left: A C
    right: A C
    up: A C
    down: A C
  resource2:
    left: A B C
    right: A B C
    up: A B C
    down: A B C
config4:
  resQuantity : 3 4 8
  resource0:
    left: B C
    right: B C
    up: B C
    down: B C
  resource1:
    left: A C
    right: A C
    up: A C
    down: A C
  resource2:
    left: A B
    right: A B
    up: A B
    down: A B
config5:
  resQuantity : 6 3 6
  resource0:
    left: A B C
    right: A B C
    up: A B C
    down: A B C
  resource1:
    left: A
    right: A
    up: A
    down: A
  resource2:
    left: A
    right: A
    up: A
    down: A
config6:
  resQuantity : 6 6 3
  resource0:
    left: A C
    right: A C
    up: A B
    down: A B
  resource1:
    left: B
    right: B
    up: A
    down: A
  resource2:
    left: A C
    right: A C
    up: C
    down: C
config7:
  resQuantity : 6 6 3
  resource0:
    left: A B
    right: A B
    up: A C
    down: A C
  resource1:
    left: A
    right: A
    up: B
    down: B
  resource2:
    left: X
    right: X
    up: A
    down: A
config8:
  resQuantity : 6 6 3
  resource0:
    left: A B
    right: A B
    up: A
    down: A
  resource1:
    left: A B
    right: A B
    up: B
    down: B
  resource2:
    left: X
    right: X
    up: X
    down: X
config9:
  resQuantity : 5 5 5
  resource0:
    left: B
    right: B
    up: X
    down: C
  resource1:
    left: A
    right: A
    up: C
    down: X
  resource2:
    left: X
    right: X
    up: A
    down: B